query Login($auth: AuthInput!) {
  login(auth: $auth) {
    user {
      id
      email
      role
      profile {
        first_name
        last_name
        full_name
        avatar
      }
      position_name
    }
    access_token
    refresh_token
  }
}

mutation Signup($auth: AuthInput!) {
  signup(auth: $auth) {
    user {
      id
      email
      role
      profile {
        first_name
        last_name
        full_name
        avatar
      }
      position_name
    }
    access_token
    refresh_token
  }
}

mutation UpdateToken {
  updateToken {
    access_token
    refresh_token
  }
}