query GetProfileLanguages($userId: ID!) {
  profile(userId: $userId) {
    id
    languages {
      name
      proficiency
    }
  }
}

query GetLanguages {
  languages {
    id
    iso2
    name
    native_name
  }
}

mutation CreateLanguage($language: CreateLanguageInput!) {
  createLanguage(language: $language) {
    id
    iso2
    name
    native_name
  }
}

mutation UpdateLanguage($language: UpdateLanguageInput!) {
  updateLanguage(language: $language) {
    id
    iso2
    name
    native_name
  }
}

mutation DeleteLanguage($languageId: ID!) {
  deleteLanguage(language: { languageId: $languageId }) {
    affected
  }
}

mutation AddProfileLanguage($language: AddProfileLanguageInput!) {
  addProfileLanguage(language: $language) {
    id
    languages {
      name
      proficiency
    }
  }
}

mutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {
  updateProfileLanguage(language: $language) {
    id
    languages {
      name
      proficiency
    }
  }
}

mutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {
  deleteProfileLanguage(language: $language) {
    id
    languages {
      name
      proficiency
    }
  }
}
